apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetcher
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fetcher
              image: crypto-aggregator-fetcher:latest
              imagePullPolicy: IfNotPresent
              env:
              - name: COINCAP_API_KEY
                value: ""
              - name: POSTGRES_DSN
                value: "host=postgres user=postgres password=postgres dbname=crypto port=5432 sslmode=disable"
          restartPolicy: OnFailure