apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-api
  template:
    metadata:
      labels:
        app: graphql-api
    spec:
      containers:
        - name: graphql-api
          image: crypto-aggregator-graphql-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: POSTGRES_DSN
              value: "postgres://postgres:postgres@postgres:5432/crypto"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 20