services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  fetcher:
    build: ./services/fetcher
    environment:
      - COINCAP_API_KEY=
      - POSTGRES_DSN=host=postgres user=postgres password=postgres dbname=crypto port=5432 sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  graphql-api:
    build: ./services/graphql-api
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/crypto
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis